Rj/landing page
csesoc/Structs.sh pull request #240
Opened 2022-06-13 02:32 UTC by justneocity

Created a landing page with topic cards. Currently all topic images are stored and used locally. I didn't add it to the db yet since it takes effectiveness immediately and I didn't want to break anything. Organised code as well into style modules. Page responsiveness should be okay too. Let me know if there are any changes to make:)

2022-06-19 04:53 UTC, strayacode reviewed
apart from small comment lgtm

2022-06-19 04:53 UTC, strayacode commented on client/src/components/Topics/TopicCard.tsx
> +const images = [linked, binary, graph, binary];
The 3rd one should be just be binary because it's an avl tree. When sorting algos gets merged in we can make an image for it

2022-06-23 13:34 UTC, jlin2002 requested changes
Are binary-search-tree-nobg.png and the other black data structure images still getting used? If not, could you delete any images that are no longer getting used?
Delete empty Topics.module.scss file.

2022-06-23 13:34 UTC, jlin2002 commented on client/src/components/Topics/TopicCard.tsx
> +    <div>
Is there a reason why this is wrapped around a div?

2022-06-23 13:34 UTC, jlin2002 commented on client/src/components/Topics/Topics.tsx
> +        <div
There will be a bit of a div soup happening here. Can you define the onClick handler inside the TopicCard? Also, is it possible to just change the topic card to an \<a\> component (add "display: block" styling) whose href is /visualiser/....... etc.?

2022-06-25 07:08 UTC, jlin2002 approved these changes

2022-06-25 07:22 UTC, merged